# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 208dd19823958d20dfeac95085c8d572f2b1a6d0ed10c540307491eded9e5c60b45f61a6aa782af933d8c7ccdf2c94ec02c472ce60fd65046bb6c7d859785606

test:
  secret_key_base: b1f7c7de1032e518634e67fc33b183dca9fb01591e306ca6eb2a64a45a8d547f561c207db9b1f989d11257cbc44e7bf86530d54a258b1058bc4a48ec2d1d0172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
